### ISSUE TITLE
Add gdx-holo skin

### ISSUE THREAD

**Issue by kotcrab** [czyzby/gdx-skins#1]
Seems to be similar to holo skin by Carsten but I think it's still worth listing here. https://github.com/nooone/gdx-holo

**Comment by czyzby** [comment]
Looks nice, but since there's no license in the repository, we mind need a permission first. https://github.com/nooone/gdx-holo/issues/1

**Comment by nooone** [comment]
Well, it's really very similar to the other one you have and it comes only with a single color and size, but if you want to include it, you can. It's slightly different in some places and has some additional things like a "card" drawable though.

**Comment by czyzby** [comment]
I suspected there are some subtle differences here and there, so it might make sense to include it as an alternative to the existing one. Who knows, it might be useful for someone - and listing all free skins in this repository was kind of the whole point.
