### ISSUE TITLE
Craftacular UI

### ISSUE THREAD

**Issue by raeleus** [czyzby/gdx-skins#2]
Awhile back you asked me to make an issue when I complete new skins. I just uploaded Craftacular UI which mimics the appearance of the Minecraft interface.

https://ray3k.wordpress.com/craftacular-ui-skin-for-libgdx/

You're pretty fast at updating this so you're probably already on top of it. Thanks for keeping this repository up-to-date.

**Comment by czyzby** [comment]
Thanks for the update. Your skin contributions are great, but it would be **really** nice if you also included the raw assets in your packages. I think most people would like to edit the skins at some point, and while they can use your Skin Composer to do that (_actually, that's what I'm using to extract the raw assets in the first place_), not everyone knows about it or wants to use it at all.

(Also, ignore the commit hell. I messed up some Git preferences. Oh, well.)

**Comment by raeleus** [comment]
That's a great idea! I'll make sure to do that with my future releases and updates. By the way, I'm hoping to do a total of 100 before I get bored of it. We'll see how that goes.

Oh, and Git is perplexing to me sometimes. Don't ever push a mistake because there isn't a damn way to fix it cleanly.

**Comment by czyzby** [comment]
100? Nice! I wish more people knew about this, it is certainly a great contribution for the LibGDX community.

You could try creating some more flexible skins that could be easily recolored in code. `TintedDrawable` can be (over)used to quickly prototype your UI and try different themes with an edit of a single JSON line. Check out [Kenney Pixel](https://github.com/czyzby/gdx-skins/tree/master/kenney-pixel) or [Tinted](https://github.com/kotcrab/vis-ui-contrib/tree/master/skins/tinted) to see what I mean.
