### ISSUE TITLE
Neon UI Skin

### ISSUE THREAD

**Issue by raeleus** [czyzby/gdx-skins#3]
I added a skin that can easily be recolored per your suggestion some time ago. Thanks for the tip!

http://www.badlogicgames.com/forum/viewtopic.php?f=22&t=22887&p=95112#p95112

**Comment by czyzby** [comment]
Thanks, seems like a great skin for prototyping. It would be nice if you added more skins like this - being able to completely (or at least partially) recolor the GUI with one or two JSON lines is really useful. Are you planning on adding any pixel-art themes?

**Comment by raeleus** [comment]
The trouble with designing a skin that can be recolored is that it restricts you to a monochrome pallet (Unless you're willing to risk unpredictable mixes of colors). I'll still keep it as an option when the opportunity arises.

I've been avoiding pixel art because I'm not any good at it. But that's the whole point of this excercise: to get better. I'll add it to my list, thanks.
