### ISSUE TITLE
Rainbow UI

### ISSUE THREAD

**Issue by raeleus** [czyzby/gdx-skins#6]
Hello again. I created Rainbow UI as a fun kid's theme for game menus.

https://ray3k.wordpress.com/rainbow-ui-skin-for-libgdx/

Thanks for your consideration.

**Comment by czyzby** [comment]
Done. Thanks for all of your skins!

**Comment by raeleus** [comment]
No problem! Thanks for your commitment to this repository.

**Comment by czyzby** [comment]
It's not a big deal, submitting a new skin takes literally minutes. It definitely takes more to create one.
