### ISSUE TITLE
Flat Earth UI

### ISSUE THREAD

**Issue by raeleus** [czyzby/gdx-skins#7]
Hello. I've been inactive for a couple weeks, but I managed to get this skin finished today:

https://ray3k.wordpress.com/flat-earth-ui-skin-for-libgdx/

Thanks!

**Comment by czyzby** [comment]
This one actually has some widgets that look pretty modern, but the palette could use some work. I hope you can recolor the skin with JSON parameters. ; )

I'll add it soon.

**Comment by czyzby** [comment]
Yes, you can! Nice! Good contribution.

**Comment by raeleus** [comment]
Thanks. And you're right about the palette. I'll test some new colors at some point. It did look a lot better on one of my monitors :/
