### ISSUE TITLE
Arcade UI and Tracer UI

### ISSUE THREAD

**Issue by raeleus** [czyzby/gdx-skins#8]
Hello,
I've added two new skins for your consideration.

https://ray3k.wordpress.com/arcade-ui-skin-for-libgdx/
https://ray3k.wordpress.com/tracer-ui-skin-for-libgdx/

Thanks again.

**Comment by dranikpg** [comment]
Hey Raeleus, I really like your artwork, so I've one petition for you : if possible, couldn't you create a skin, wich looks like this UI kit http://pixelkit.com/kits/flat-ui-kit
I think this would fit very good in this collection, because maybe somebody is missing a neutral and "modern" skin.

**Comment by raeleus** [comment]
Thanks! My attempt at a flat style ui is [Flat Earth](https://github.com/czyzby/gdx-skins/tree/master/flat-earth). You just have to go in to the JSON and modify the ugly colors into something mainstream. I mean, flat ui really is just a bunch of rectangles formatted with nice colors. Anyway, I'll give that another go soon if you still want it.

**Comment by czyzby** [comment]
You might also want to give [VisUI](https://github.com/czyzby/gdx-skins/tree/master/vis) a try.

**Comment by czyzby** [comment]
Sorry for the delay - holidays. I uploaded all of your recent skins. Thanks.

**Comment by raeleus** [comment]
No worries! I imagined you were somwhere exotic and off the grid. Happy new year.
